services:
  backend:
    build:
      context: .
      target: development
    command: npm run start:dev
    env_file:
      - .env
    depends_on:
      - postgres
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - '3006:3006'

  mongodb-primary:
    image: mongo
    restart: always
    volumes:
      - 'mongodb_master_data:/data/mongodb'
    ports:
      - '27017:27017'

volumes:
  mongodb_master_data:
    driver: local
